### ISSUE TITLE
Restructure code for zppy plugin

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/ChemDyg#7] opened 2023-04-27 22:06 UTC
@hsiangheleellnl  and @tangq: I'm working on modifying zppy plugins to load and use external python modules. But I think the ChemDyg code needs more restructuring before I can go any further.

I was able to install chemdyg in my conda development environment:

```
git clone git@github.com:E3SM-Project/ChemDyg.git
cd ChemDyg
pip install .
```
I can successfully load the module

```
python
>>> import chemdyg
```
However, I cannot import the top level function that zppy will need to call. That function should be called'`chemdyg`, but it currently called `e3sm_chem_diags`. Also, it needs to be importable using something like

```
from chemdyg import chemdyg
```

**Comment by hsiangheleellnl** [comment] 2023-04-27 22:26
@golaz Could you checkout to my version 'hsiangheleellnl/ChemDyg'? I did change the name to chemdyg but my version can't merge to main now.

**Comment by golaz** [comment] 2023-04-27 22:56
Thanks, @hsiangheleellnl.

That's better, but still not exactly what I was looking for. To directly access the top level function, I need to do the following:

```
python
>>> from chemdyg.chemdyg import chemdyg
>>> chemdyg()
```

I was hoping for something like

```
python
>>> from chemdy import chemdyg
>>> chemdyg()
```
Maybe the main function `chemdyg` needs to be in a different file? `__main__.py` or `__init__.py` Or something else should be changed?

This is probably a very elementary Python question, tagging @xylar to shed some light.

**Comment by xylar** [comment] 2023-04-28 09:11
To get what @golaz is after, the function `chemdyg` would either need to live in `chemdyg/__init__.py` or would need to be imported from somewhere else in that file.  The problem is that you can't add:
```
from chemdyg.chemdyg import chemdyg
```
to `chemdyg.__init)__.py` because it then can't tell whether `chemdyg.chemdyg` refers to the function or the module.  The solution would be not to use the same name for so many things.  I would put the function `chemdyg()` in a module called `main.py` instead.  Then, you don't have the problem.  In `chemdyg/__init__.py`, you can do:
```
from chemdyg.main import chemdyg
```
And after that, @golaz should be able to do:
```
from chemdyg import chemdyg
```
and that would be identical to:
```
from chemdyg.main import chemdyg
```

Let me know if there are further questions.

**Comment by golaz** [comment] 2023-04-28 22:01
@xylar : perfect, exactly what I needed!

@hsiangheleellnl : I had to also make some additional code modifications to ChemDyg. They are in https://github.com/E3SM-Project/ChemDyg/pull/8. Please test those in conjunction with this PR.

**Comment by hsiangheleellnl** [comment] 2023-05-18 16:48
@xylar The current ChemDyg version can work with the zppy plugin. Can we preceed to the next step of making it a conda-forge package?

**Comment by xylar** [comment] 2023-05-18 22:15
@hsiangheleellnl, that's exciting!  I will make a test conda recipe as soon as I can.  We can use that to create a conda package for testing with zppy.  We'll want to test things out before we actually make a release and submit the recipe to conda-forge.

**Comment by xylar** [comment] 2023-05-18 22:23
There are 2 copies of most requirements here:
https://github.com/E3SM-Project/ChemDyg/blob/main/setup.cfg#L22-L35
This needs to be cleaned up.  If you make a clean-up PR to fix this (but don't merge it yet), that would be great!  Then, I can point out other issues (if any) as they arise.

**Comment by xylar** [comment] 2023-05-18 22:37
Okay, I have a recipe that works (the redundant dependencies above aren't a problem, but they still should be cleaned up):
https://github.com/xylar/staged-recipes/blob/add-chemdyg/recipes/chemdyg/meta.yaml

What I will do is build the package on my laptop and upload it to a temporary place so you can try it out in a zppy development environment.  I'll give you instructions shortly as soon as the package has been uploaded.

**Comment by xylar** [comment] 2023-05-18 22:46
Okay, it's in place.  Follow the usual instructions to create a `zppy` development environment:
https://e3sm-project.github.io/zppy/_build/html/main/getting_started.html#b-development-environment

When you get to this step:
```
conda env create -f conda/dev.yml
conda activate zppy_dev
```
Follow that with this:
```
conda install -y -c e3sm/label/chemdyg_dev chemdyg
```
That should install the test package I just uploaded. Please make sure not to try to also install chemdyg some other way (e.g. out of a local repo) because we want to test the conda package.

Then, run whatever tests you have been using in zppy to test `chemdyg`.  They should work the same way if we have done this right.  But let's be realistic -- things hardly ever work on the first try.  So if (when?) there are errors, please report back here and we'll figure them out.

**Comment by hsiangheleellnl** [comment] 2023-05-19 01:10
@xylar I assume I do not need to git clone ChemDyg (I can't either). I created a new environment and then ran `pip install .`. After that, I tried to ran `zppy -c ChemDyg_example_script.cfg`, the error messages show 

> (zppy_chemdyg_v0.1.0) [ac.lee1061@chrlogin2 ChemDyg_zppy_final]$ zppy -c ChemDyg_example_script.cfg 
> Traceback (most recent call last):
>   File "/home/ac.lee1061/zppy_code/zppy/conda/envs/zppy_chemdyg_v0.1.0/lib/python3.9/site-packages/zppy/__main__.py", line 51, in main
>     plugin_module = importlib.import_module(plugin_name)
>   File "/home/ac.lee1061/zppy_code/zppy/conda/envs/zppy_chemdyg_v0.1.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'chemdyg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ac.lee1061/zppy_code/zppy/conda/envs/zppy_chemdyg_v0.1.0/bin/zppy", line 8, in <module>
>     sys.exit(main())
>   File "/home/ac.lee1061/zppy_code/zppy/conda/envs/zppy_chemdyg_v0.1.0/lib/python3.9/site-packages/zppy/__main__.py", line 53, in main
>     raise ValueError(
> ValueError: Could not load external zppy plugin module chemdyg

Any suggestions?

**Comment by xylar** [comment] 2023-05-19 01:20
@hsiangheleellnl, could you please list here every step you took to create your zppy dev environment?

Could you also share the results of
```
conda list chemdyg
```
?

**Comment by xylar** [comment] 2023-05-19 02:14
I'm not in a position to test `zppy` with `chemdyg` myself but here's what I ran.  Note that I deviated from the zppy instructions by using the `mamba` command rather than the `conda` command (much, much faster!) in several places:
```
git clone git@github.com:E3SM-Project/zppy.git
cd zppy
git checkout golaz/plugins
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install -y mamba
mamba clean --all -y
mamba remove --all -y -n zppy_dev
mamba env create -f conda/dev.yml
conda activate zppy_dev
mamba install -y -c e3sm/label/chemdyg_dev chemdyg
pre-commit install
python -m pip install .
python -c "import chemdyg"
```
That last command passed fine for me, indicating that the `chemdyg` python package should be available for importing.

**Comment by xylar** [comment] 2023-05-19 02:18
@hsiangheleellnl, a tip is also to use:
````
```
````
that is, triple-back-quote (the character below the tilde `~` on my keyboard) instead of `>` to quote code or command-line output.  It comes out looking more like what you expect.

**Comment by hsiangheleellnl** [comment] 2023-05-23 17:52
@xylar Thank you for the detail instruction. Following your instruction (including use mamba), I can successfully running zppy with chemdyg package.  Thank you!!

I have a question. Since ChemDyg became a package in zppy, where I should update my source code if there is any changes in the future.

**Comment by tangq** [comment] 2023-05-23 17:57
This is great. It seems that the `zppy` and `chemdyg` packages work fine together.

@xylar, are we ready to make the first release now?

**Comment by xylar** [comment] 2023-05-23 18:37
Yes, go ahead with a release!  Congratulations!

See these examples for what is nice to include in a release:
https://github.com/MPAS-Dev/MPAS-Analysis/releases

**Comment by xylar** [comment] 2023-05-23 18:40
> I have a question. Since ChemDyg became a package in zppy, where I should update my source code if there is any changes in the future.

@hsiangheleellnl, my understanding is that ChemDyg is still a plugin to zppy.  Did that plan change?  If the ChemDyg source code is now part of zppy, you would edit it there.  If not, it is a plugin and not part of zppy itself.  The only place to edit the source code is here in this repo (or obviously your fork if you have one, like I do).  You would make PRs here until you are ready to make another release.  You would test the code before the release happens just as you have (without the conda package) up until recently.  Then, you will make a release again, as you are about to do and you would make a PR into zppy to tell it to use the new release instead of the old one.

**Comment by xylar** [comment] 2023-05-23 18:41
That complex workflow is part of the reason that incorporating this work into E3SM-Diags would probably lead to quicker updates and a smoother workflow eventually.

**Comment by tangq** [comment] 2023-05-23 18:45
> Yes, go ahead with a release! Congratulations!
> 
> See these examples for what is nice to include in a release: https://github.com/MPAS-Dev/MPAS-Analysis/releases

Thank you, @xylar . It seems that PR https://github.com/E3SM-Project/ChemDyg/pull/9 is appending your approval to be merged and included in the first release.

**Comment by xylar** [comment] 2023-05-23 22:26
Sorry about that.  I lost track of that PR.  Thanks for the reminder.  I just approved.

**Comment by tangq** [comment] 2023-05-23 22:28
No worries, @xylar . @hsiangheleellnl and I will create the release soon based on your example.

**Comment by golaz** [comment] 2023-05-23 23:37
@hsiangheleellnl : just to confirm what @xylar indicated. ChemDyg is not part of zppy, but it can be called from zppy. ChemDyg will need to be maintained and kept up to date by you or @tangq to ensure that it continues to work with zppy in the future. I don't think the Infrastructure Group has sufficient resources to incorporate and then by extension maintain every new diagnostics into E3SM Diags.

**Comment by hsiangheleellnl** [comment] 2023-05-23 23:49
Why I have this question is because when I followed @xylar guidence, I did not need to download ChemDyg. I think I am confused by this command ```conda install -y -c e3sm/label/chemdyg_dev chemdyg```. As a user, I know where to change the source code if I need, since ChemDyg is a conda package. But as a developer, I do not know if I have a new release version, will this command automatically link to the new version?

**Comment by xylar** [comment] 2023-05-23 23:54
@hsiangheleellnl, in the future, we will not use the special channel `-c e3sm/label/chemdyg_dev`.  That was for development.  In the future, you will install `chemdyg` along with `zppy` and the latest release version will be installed unless you specify a version.  To create a conda environment with the latest zppy and chemdyg, you would run:
```
mamba create -y -n my_diag_env zppy chemdyg
mamba activate my_diag_env
```

If you want a specific version of dhemdyg, say relase 0.1.0, you would run:
```
mamba create -y -n my_diag_env zppy chemdyg=0.1.0
mamba activate my_diag_env
```

**Comment by xylar** [comment] 2023-05-23 23:54
You will not use the is approach as a developer, just as a user who doesn't want to modify the code (presumably an E3SM-Unified user).

**Comment by xylar** [comment] 2023-05-23 23:54
You will not use the is approach as a developer, just as a user who doesn't want to modify the code (presumably an E3SM-Unified user).

**Comment by hsiangheleellnl** [comment] 2023-05-23 23:56
That is clear. Thank you, @xylar !

**Comment by xylar** [comment] 2023-05-23 23:56
As a developer, you will continue to use the approach that you were using before, presumably a workflow that you discussed with @golaz and which I don't think I was involved in.

**Comment by golaz** [comment] 2023-05-24 04:37
@xylar: somewhat off-topic here, but let me try to succinctly explain some of my design goals for zppy plugins.

Let's take the typical lifecycle of a software package

1. Creation
2. Maintenance and support
3. Sunset

Most of the hard and creative work takes place during (1). (2) is important but also expensive, especially for a project with limited resources. (3) is often overlooked because of the difficulty to be proactive about it.

Zppy plugins are intended to help with all the steps, but especially with (2) and (3). With (2) because there is a clear delineation of the responsibilities. Zppy maintains the plugin infrastructure in its code base, while the plugin developers maintain the plugin itself. Should a plugin outlive its useful life or its developers loose interest, maintenance will naturally stop. The plugin package gets dropped from E3SM Unified and as a result graciously sunsets without any dead code sediment left behind in zppy or E3SM Diags.

**Comment by xylar** [comment] 2023-05-24 05:38
@golaz, thanks for explaining.  That sounds promising.

From my perspective, it feels like these plugins might:
1. Be hard for anyone but the developers to use or contribute to because they don't need to conform to existing software conventions
2. Require significant initial work from infrastructure on getting each plugin to be a python package and to get it up on conda-forge

But I recognize that plugins offer quite a lot of flexibility for the developers so I am perfectly willing to give this a try.

**Comment by tangq** [comment] 2023-05-25 23:42
@xylar and @golaz , @hsiangheleellnl just created the first release (v0.1.0) for ChemDyg. I guess the next step is to put chemdyg on conda-forge and `e3sm_unified` will then include the conda-forge version in its next release. Please let @hsiangheleellnl or me know any actions are needed from our side. Thank you.

**Comment by xylar** [comment] 2023-05-25 23:51
Great!  I just submitted the recipe to conda-forge:
https://github.com/conda-forge/staged-recipes/pull/22918

Please respond to my comment that you are willing to be maintainers.

This may take 1-3 weeks before the recipe gets merged.  If it takes a while, don't worry too much.  I will make sure we have a way of testing in E3SM-Unified.

**Comment by xylar** [comment] 2023-05-25 23:55
Great, thanks for replying!

Once the CI tests pass on the recipe, I will request a review and the waiting begins...

**Comment by tangq** [comment] 2023-05-25 23:59
I noticed that @hsiangheleellnl and I were asked to review https://github.com/conda-forge/staged-recipes/pull/22918.

@xylar , do we need to approve the PR like in other repos?

**Comment by xylar** [comment] 2023-05-26 00:11
You have not been asked to review. I also thought so at first. That is just how GitHub shows that you have commented on the PR. No need to review it. I'm not sure you would even have permission to do so.

**Comment by tangq** [comment] 2023-05-26 01:45
Got it.

**Comment by xylar** [comment] 2023-07-27 08:38
I think this issue has been addressed and can probably be closed.

**Closed as completed** 2023-07-27 17:45 UTC
